[package]
name = "rustdef"
version = "0.1.0-alpha.2"
authors = ["Ryosuke Kamesawa <emak.ryo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustdef"
crate-type = ["cdylib", "rlib"]

[build-dependencies]
glob = "0.3"
zip = "0.5"

[dependencies]
quote = "1.0"
zip = "0.5"
numpy = { version = "0.7", optional = true }
ndarray = { version = "0.13", optional = true }
syn = { version = "1.0", features = ["full"] }
pyo3 = { version = "0.8", features = ["extension-module"] }

[features]
default = ["numpy-bridge", "core"]
core = []
numpy-bridge = ["numpy", "ndarray"]

[package.metadata.maturin]
requires-dist = ["maturin", "jupyter"]
classifier = [
    "Framework :: Jupyter",
    "Framework :: IPython",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Rust",
]
requires-python = ">=3.6"
requires-external = ["rust"]
project-url = ["Github, https://github.com/emakryo/rustdef"]
