[package]
name = "rustdef"
version = "0.1.0"
authors = ["Ryosuke Kamesawa <emak.ryo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustdef"
crate-type = ["cdylib", "rlib"]

[build-dependencies]
glob = "0.3"
zip = "0.5"

[dependencies]
quote = "1.0.2"
zip = "0.5"
numpy = { version = "0.7.0", optional = true }
ndarray = { version = ">=0.12", optional = true }

[dependencies.syn]
version = "1.0.14"
features = ["full"]

[dependencies.pyo3]
version = "0.8"
features = ["extension-module"]

[features]
default = ["numpy-bridge", "core"]
core = []
numpy-bridge = ["numpy", "ndarray"]

[package.metadata.maturin]
require-dist = ["maturin", "jupyter"]