[package]
name = "rustdef"
version = "0.1.0"
authors = ["Ryosuke Kamesawa <emak.ryo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustdef"
crate-type = ["cdylib"]

[dependencies]
quote = "1.0.2"

[dependencies.syn]
version = "1.0.14"
features = ["full"]

[dependencies.pyo3]
version = "0.9.0-alpha.1"
features = ["extension-module"]

