[package]
name = "rustdef"
version = "0.2.0"
authors = ["Ryosuke Kamesawa <emak.ryo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustdef"
crate-type = ["cdylib", "rlib"]

# [build-dependencies]
# glob = "0.3.0"
# zip = "0.5.11"

[dependencies]
quote = "1.0.9"
zip = "0.5.13"
syn = { version = "1.0.72", features = ["full"] }
pyo3 = { version = "0.14.3", features = ["extension-module"] }  # version corresponds to numpy

[package.metadata.maturin]
requires-dist = ["maturin", "jupyter"]
classifier = [
    "Framework :: Jupyter",
    "Framework :: IPython",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Rust",
]
requires-python = ">=3.6"
requires-external = ["rust"]
project-url = { Github = "https://github.com/emakryo/rustdef" }
