[package]
name = "rustdef"
version = "0.1.0"
authors = ["Ryosuke Kamesawa <emak.ryo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustdef"
crate-type = ["cdylib", "rlib"]

[dependencies]
quote = "1.0.2"
numpy = "0.7.0"
ndarray = ">=0.12"

[dependencies.syn]
version = "1.0.14"
features = ["full"]

[dependencies.pyo3]
version = "0.8"
features = ["extension-module"]

