name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        # Version range or exact version of a Python version to use, using semvers version range syntax.
        python-version: 3.x # optional, default is 3.x
        # The target architecture (x86, x64) of the Python interpreter.
        architecture: x64 # optional, default is x64
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.3.1
      with:
        # The toolchain name, such as stable, nightly, or 1.8.0
        rust-version: nightly # optional, default is stable
        # The toolchain components to install, comma-separated
        # components: # optional, default is 
        # The toolchain targets to add, comma-separated
        # targets: # optional, default is 
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
    - name: Install build dependencies
      run: pip install maturin jupyter
    - name: Build wheel
      run: maturin build
    - name: Execute examples
      run: jupyter-nbconvert --execute examples/*.ipynb
