name: Test

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.6, 3.7, 3.8, 3.9]
        include:
          - python: 3.6
            python-name: cp36
          - python: 3.7
            python-name: cp37
          - python: 3.8
            python-name: cp38
          - python: 3.9
            python-name: cp39

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        # Version range or exact version of a Python version to use, using semvers version range syntax.
        python-version: ${{ matrix.python }} # optional, default is 3.x
        # The target architecture (x86, x64) of the Python interpreter.
        architecture: x64 # optional, default is x64
    - name: Set up a Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        # The toolchain name, such as stable, nightly, or 1.8.0
        toolchain: stable # optional, default is stable
        # The toolchain components to install, comma-separated
        components: clippy # optional, default is
        # The toolchain targets to add, comma-separated
        # targets: # optional, default is
    - name: Install build dependencies
      run: pip install maturin jupyter numpy flake8
    - name: Install runtime dependencies
      run: cargo install cargo-edit
    - name: Python syntax check
      run: flake8
    - name: Rust lint
      run: cargo clippy
    - name: Build wheel
      run: |
        maturin build --release
        ls target/wheels
    - uses: actions/upload-artifact@v1
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.python-name}}
        path: target/wheels
    - name: Install wheel
      shell: bash
      run: pip install target/wheels/rustdef-*${{ matrix.python-name }}*.whl
    - name: Execute examples
      shell: bash
      # Skip numpy.ipynb due to problem w/ pyo3 https://github.com/PyO3/rust-numpy/issues/97
      # ##[error]thread '<unnamed>' panicked at 'An error occurred while initializing class SliceBox', rustdef_cell_4f1f27901aca8ef8c2b7ba8fd8a3fd78760e5ae7/src/lib.rs:1:1
      run: jupyter-nbconvert --to html --debug --stdout --ExecutePreprocessor.timeout=-1 --execute 'Get started.ipynb' types.ipynb numpy.ipynb
      working-directory: examples

  test:
    needs: build

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.6, 3.7, 3.8, 3.9]
        include:
          - python: 3.6
            python-name: cp36
          - python: 3.7
            python-name: cp37
          - python: 3.8
            python-name: cp38
          - python: 3.9
            python-name: cp39

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.python-name }}
        path: wheels
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        # Version range or exact version of a Python version to use, using semvers version range syntax.
        python-version: ${{ matrix.python }} # optional, default is 3.x
        # The target architecture (x86, x64) of the Python interpreter.
        architecture: x64 # optional, default is x64
    - name: Set up a Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        # The toolchain name, such as stable, nightly, or 1.8.0
        toolchain: stable # optional, default is stable
        # The toolchain components to install, comma-separated
        # components: # optional, default is
        # The toolchain targets to add, comma-separated
        # targets: # optional, default is
    - name: Install wheel
      run: pip install wheels/rustdef-*${{ matrix.python-name }}*.whl
    - name: Install additional dependencies
      run: pip install numpy
    - uses: actions/checkout@v2
    - name: Execute examples
      shell: bash
      run: jupyter-nbconvert --to html --debug --stdout --ExecutePreprocessor.timeout=-1 --execute 'Get started.ipynb' types.ipynb numpy.ipynb
      working-directory: examples
